# Generated by Django 5.0.6 on 2024-08-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatamahasiswa',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
