# Generated by Django 5.0.6 on 2024-08-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_matakuliah_jadwalkuliah_nilaimahasiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalkuliah',
            name='matkul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.matakuliah'),
        ),
        migrations.AlterField(
            model_name='nilaimahasiswa',
            name='matkul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.matakuliah'),
        ),
    ]
