# Generated by Django 5.0.6 on 2024-08-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_jadwalkuliah_matkul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimahasiswa',
            name='matkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.matakuliah'),
        ),
    ]
